pipeline:
  identifier: Build_harness_1698339858434
  name: Build harness
  orgIdentifier: default
  projectIdentifier: mphasis1
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: org.githubconnectorcorrect
        repoName: harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
